# This is a basic workflow to help you get started with Actions

name: Build_LaTeX

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install software
        run: sudo apt update && sudo apt install latexmk texlive-latex-extra
      - name: check out with git lfs
        run: git lfs pull
      - name: make LaTeX document
        run: make
        
      - uses: meeDamian/github-release@2.0
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            tag: ${{ env.TAG }}
            files: > 
              project_proposal/report.pdf
