name: LaTeX CI draft

on:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master
        
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v2
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make
            
      - uses: actions/upload-artifact@v2
        with:
          name: draft
          path: report.pdf
          
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT1 }}
          repository: kepet19/management
          event-type: upload-artifacts
          client-payload: '{"prnumber": "${{ github.event.number }}", "checkrunid": "${{ github.run_id }}"}'
